### ISSUE TITLE
In Test.ipynb, `image = gen_load.__next__()` where gen_load is undefined?

### ISSUE THREAD

**Issue by LUYU0004** [cyclomon/3dbraingen#4]

**Comment by cyclomon** [comment]
Sorry, there was a mistake. 
after declaring inf_train_gen ( code for infinite data loader ),
there should have been a code "gen_load = inf_train_gen(train_loader)"
I included this line.

Thanks.

**Comment by LUYU0004** [comment]
Thank you for your reply! 
And there is another minor issue: in `pytorch_ssim.py`, the `filters` variable in create_window(..) function is undefined.
